[package]
name = "mpm-pitch"
version = "0.1.0"
authors = ["Per Gantelius <per@stuffmatic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"
rand_seeder = "*"
rand_pcg = "*"
serde = "*"
crossbeam-queue = { git = "https://github.com/stjepang/crossbeam", branch = "spsc" }
portaudio = "*"
tokio = { version = "0.2", default-features = false, features = ["io-std", "macros", "stream", "time"] }
tokio-tungstenite = "*"
futures-channel = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }

[[bench]]
name = "pitch_detection_result"
harness = false

[dependencies]
microfft = "0.3.0"
