[package]
name = "mpm-pitch"
version = "0.1.0"
authors = ["Per Gantelius <per@stuffmatic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfft = "3.0.1"
