[package]
name = "mpm-pitch"
version = "0.1.0"
authors = ["Per Gantelius <per@stuffmatic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"
dev_helpers = { path = "dev_helpers" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

# TODO: should be encapsulated in dev_helpers?
crossbeam-queue = { git = "https://github.com/stjepang/crossbeam", branch = "spsc" }

[[bench]]
name = "result"
harness = false

[dependencies]
microfft = { path = "../microfft-rs"}
