[package]
name = "mpm-pitch"
version = "0.1.0"
authors = ["Per Gantelius <per@stuffmatic.com>"]
edition = "2018"
description = "An implementation of the MPM (McLeod Pitch Method) pitch detection algorithm. Reasonably performant and no_std compatible."
repository = "https://github.com/stuffmatic/mpm-pitch/"
license = "MIT"
categories = ["no-std", "multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"
dev_helpers = { path = "dev_helpers" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[[bench]]
name = "result"
harness = false

[dependencies]
microfft = { git = "https://gitlab.com/ra_kete/microfft-rs", commit = "7dd9b92c"}
micromath = "*"
