[package]
resolver = "2"
name = "micro-ear"
version = "0.1.0"
authors = ["Per Gantelius <per@stuffmatic.com>"]
edition = "2018"
description = "A reasonably performant and no_std compatible implementation of the MPM (McLeod Pitch Method) pitch detection algorithm"
repository = "https://github.com/stuffmatic/micro-ear/"
license = "MIT"
categories = ["no-std", "multimedia::audio", "embedded"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"
rtrb = "0.1"
portaudio = "0.7.0"

dev_helpers = { path = "dev_helpers" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"

[[bench]]
name = "main"
harness = false

[dependencies]
microfft = { version = "0.4.0" }
micromath = "*"
