[package]
name = "dev_helpers"
version = "0.1.0"
authors = ["Per <per@stuffmatic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtrb = "0.1"
crossbeam-channel = "*"
portaudio = "*"
ws = "*"
