name: Cargo build and test

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build with default features
      run: cargo build --verbose
    
    # Install a toolchain without std, used for no_std build. 
    - name: Install thumbv8m.main-none-eabihf toolchain
      run: rustup target add thumbv8m.main-none-eabihf
      
    - name: no_std build
      run: cargo build --verbose --target=thumbv8m.main-none-eabihf
  
    - name: Run tests
      run: cargo test --verbose
